create table refresh_tokens (expires_at timestamp(6) with time zone not null, id bigint generated by default as identity, user_id bigint not null unique, token varchar(255) not null unique, primary key (id));
create table users (id bigint generated by default as identity, password varchar(255) not null, username varchar(255) not null, primary key (id));
alter table if exists refresh_tokens add constraint FK1lih5y2npsf8u5o3vhdb9y0os foreign key (user_id) references users;
