CREATE TABLE summaries (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           input TEXT NOT NULL,
                           summary TEXT NOT NULL,
                           associated_user BIGINT NOT NULL,
                           CONSTRAINT fk_summaries_user
                               FOREIGN KEY (associated_user) REFERENCES users(id)
);